language: python
sudo: false
dist: trusty
python:
    - "2.7"
    - "3.6"
env:
matrix:
    allow_failures:
    - python: "3.6"
install:
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
